site_name: Hadoop notes
pages:
- index: index.md
- flume: flume.md 
theme: mkdocs
#theme: readthedocs
repo_url: https://github.com/xiuyanduan/bookDemo
markdown_extensions:
    - toc:
        permalink:
    - admonition:
